# Site
title:              Hari Erdi
bio:                'Sistem Informasi'
description:        "Moon is a minimal, one column jekyll theme for your blog."
reading_time:       true
words_per_minute:   200
logo:               'http://www.clker.com/cliparts/3/e/d/8/12422498021059320112H.svg.hi.png'
background:         'http://4.bp.blogspot.com/-kYxMblwUeuM/VI_0U_DjzdI/AAAAAAAABzA/lZKCBHEDYrA/s1600/Black%2BShoes%2BWallpaper.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://harierdi.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            aiy_17
facebook:           harierdi
github:             harierdi
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          harierdi/
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
steam:              profiles/76561198166106098/
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://harierdi/harierdi.github.io

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
